import Head from "next/head";
import Image from "next/image";
import { Caveat_Brush, Noto_Sans } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/Header/Header";
import Body from "@/components/Body/Body";
import SocialContainer from "@/components/SocialContainer/SocialContainer";

const caveat = Caveat_Brush({ subsets: ["latin"], weight: "400" });
const noto = Noto_Sans({ subsets: ["latin"], weight: "400" });

export default function Home() {
  return (
    <>
      <Head>
        <title>RatePunk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${caveat.className}`}>
        <Header fontType={noto} />
        <Body fontType={noto} />
        <SocialContainer fontType={noto} />
      </main>
    </>
  );
}
